# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-16 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181116_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
