# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-16 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_photo_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='approved',
            field=models.CharField(default=b'Disapprove', max_length=50),
        ),
    ]
