# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-16 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181116_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='approved',
            new_name='status',
        ),
    ]
