# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-16 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181116_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='status',
        ),
    ]
