# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-17 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181117_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='status',
        ),
    ]
