# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-17 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_photo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='status',
        ),
    ]
